In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
import numpy as np
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
import numpy as np
c=np.zeros((3,5))
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
import numpy as np
d=np.random.random((2,1))
print(d)

[[0.88459358]
 [0.22962623]]


In [ ]:
e=np.arange(0,36,8)
print(e)

[ 0  8 16 24 32]


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarray=arr[0:2,1:3]
print(subarray)

[[2 3]
 [5 6]]


In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[4])
print(arr[-1])
print(arr[1:4])
print(arr[arr>25])
print(arr[[1,3]])

10
50
50
[20 30 40]
[30 40 50]
[20 40]


In [10]:
import numpy as np
arr1=[10,20,30,40,50]
arr2=[6,2,7,1,4]
a=np.array(arr1)
b=np.array(arr2)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[10 20 30 40 50]
[6 2 7 1 4]
[16 22 37 41 54]
[ 4 18 23 39 46]
[ 60  40 210  40 200]
[ 1.66666667 10.          4.28571429 40.         12.5       ]


In [12]:
print(a.dot(b))
sclr=3
print("scalar value:",sclr)
print("Array:",a)
print("Result:",a*sclr)

550
scalar value: 3
Array: [10 20 30 40 50]
Result: [ 30  60  90 120 150]


In [15]:
import numpy as np
a=np.array([[10,20],[30,40]])
b=np.array([[3,7],[5,9]])
print(a%b)

[[1 6]
 [0 4]]


In [19]:
def my_func(x,y):
  if x>y:
    return x-y
  else:
    return x+y
arr1=[10,20,30,40,50]
arr2=[100,90,80,70,60]
vect_func=np.vectorize(my_func)
print("Array 1:",arr1)
print("Array 2:",arr2)
print("result:",vect_func(arr1,arr2))


Array 1: [10, 20, 30, 40, 50]
Array 2: [100, 90, 80, 70, 60]
result: [110 110 110 110 110]
